/**
 * StadiumOS AI - Global Event Constants Registry
 * Grouped by domain to avoid hardcoded string literals across the codebase.
 */
export const EVENTS = {
  SYSTEM: {
    BOOTSTRAP_COMPLETE: 'SYSTEM_BOOTSTRAP_COMPLETE',
    HEALTH_CHANGED: 'SYSTEM_HEALTH_CHANGED'
  },
  SIMULATION: {
    SIMULATION_FRAME: 'SIMULATION_FRAME',
    STATE_CHANGED: 'STATE_CHANGED'
  },
  AI: {
    AI_DECISION_FRAME: 'AI_DECISION_FRAME',
    RECOMMENDATION_CREATED: 'AI_RECOMMENDATION_CREATED'
  },
  UI: {
    LAYOUT_CHANGED: 'UI_LAYOUT_CHANGED',
    THEME_CHANGED: 'UI_THEME_CHANGED',
    PANEL_DOCK_UPDATED: 'UI_PANEL_DOCK_UPDATED',
    FOCUS_CHANGED: 'UI_FOCUS_CHANGED'
  },
  WORKER: {
    WORKER_STARTED: 'WORKER_STARTED',
    WORKER_STOPPED: 'WORKER_STOPPED',
    WORKER_CRASHED: 'WORKER_CRASHED'
  },
  DIAGNOSTICS: {
    METRICS_RECORDED: 'DIAGNOSTICS_METRICS_RECORDED'
  },
  NOTIFICATIONS: {
    NOTIFICATION_QUEUED: 'NOTIFICATIONS_NOTIFICATION_QUEUED',
    NOTIFICATION_DISPATCHED: 'NOTIFICATIONS_NOTIFICATION_DISPATCHED',
    NOTIFICATION_CLEARED: 'NOTIFICATIONS_NOTIFICATION_CLEARED'
  },
  COMMANDS: {
    COMMAND_REGISTERED: 'COMMANDS_COMMAND_REGISTERED',
    COMMAND_EXECUTED: 'COMMANDS_COMMAND_EXECUTED',
    COMMAND_PALETTE_TOGGLED: 'COMMANDS_COMMAND_PALETTE_TOGGLED'
  }
};
export default EVENTS;
